### ISSUE TITLE
@angular/material/material"' has no exported member 'TemplatePortal'.

### ISSUE THREAD

**Issue by lutsifer** [bergben/ng2-image-gallery#14]
Hello,

I used your package and everything was perfect until I had to move the project to other dev machine...
I got pretty nasty error no matter what I try it persist:
```

ERROR in long_path.../node_modules/ng2-image-gallery/dist/src/ng2-image-gallery-displacer.component.d.ts (2,10): Module '"long_path.../node_modules/@angular/material/material"' has no exported member 'TemplatePortal'.
long_path.../node_modules/ng2-image-gallery/dist/src/ng2-image-gallery-displacer.component.d.ts (2,26): Module '"long_path.../@angular/material/material"' has no exported member 'Overlay'.

ERROR in PortalModule is not an NgModule
```
Please help, I am pretty despaired already :)
I don't remember how I made it work the first time (I remember there was some problems but maybe not exactly like this..)

So I stuck with working dev version only if I reproduce node and npm versions and using ziped directory... not solution at all..

**Comment by lutsifer** [comment]
Any help will save my life, thank you!

**Comment by bergben** [comment]
Hey @lutsifer,

unfortunately the dependency on angular/material creates nothing but trouble... see #9 
I tried to fix the dependency on it to the version that was used when releasing the last version of this module. Can you try if it works with ng2-img-gallery at version `0.3.19` ?

**Comment by lutsifer** [comment]
It looks a bit worse then before?

```
ERROR in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/node_modules/@angular/material/core/typings/bidi/index.d.ts (8,26): Module '"long_path_here.../ng2-castifyme/node_modules/@angular/cdk/bidi"' has no exported member 'DIRECTIONALITY_PROVIDER'.

ERROR in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/node_modules/@angular/material/core/typings/rxjs/rx-chain.d.ts (8,25): Cannot find module '@angular/cdk/rxjs'.

ERROR in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/node_modules/@angular/material/core/typings/rxjs/rx-operators.d.ts (8,574): Cannot find module '@angular/cdk/rxjs'.

ERROR in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/node_modules/@angular/material/table/typings/row.d.ts (20,39): Generic type 'CdkRowDef<T>' requires 1 type argument(s).
long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/node_modules/@angular/material/table/typings/row.d.ts (23,40): Generic type 'CdkRowDef<T>' requires 1 type argument(s).

ERROR in Metadata version mismatch for module long_path_here.../ng2-castifyme/node_modules/@angular/cdk/overlay/typings/index.d.ts, found version 4, expected 3, resolving symbol Ng2ImageGalleryModule in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/dist/src/ng2-image-gallery.module.d.ts, resolving symbol Ng2ImageGalleryModule in long_path_here.../ng2-castifyme/node_modules/ng2-image-gallery/dist/src/ng2-image-gallery.module.d.ts
```
